version: 2
jobs:
  build:
    docker:
      - image: cimg/node:17.4.0
    steps:
      - checkout
      - run: echo "run npm install"
      - run: npm install
      - run: CI=true npm run build
  test:
    docker:
      - image: cimg/node:17.4.0
    steps:
      - checkout
      - run: echo "run tests"
      - run: npm test
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
